version: 2.1
orbs:
  docker: circleci/docker@2.0.3

jobs:

  deploy8266:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/arduino-docker-build
          dockerfile: ./Dockerfile.esp8266
          tag: esp8266
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/arduino-docker-build
          tag: esp8266
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            docker tag $(</tmp/digest.txt) suculent/arduino-docker-build:esp8266
  

  deploy32:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/arduino-docker-build
          dockerfile: ./Dockerfile.esp32
          tag: esp32
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/arduino-docker-build
          tag: esp32
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            docker tag $(</tmp/digest.txt) suculent/arduino-docker-build:esp32
  
  deployFat:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/arduino-docker-build
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/arduino-docker-build
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            docker tag $(</tmp/digest.txt) suculent/arduino-docker-build:latest

  test:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/arduino-docker-build
          tag: future

#
# WORKFLOWS
#

workflows:
  version: 2
  build:
    jobs:
      - test:
          context:
            - dockerhub
      - deployFat:
          context:
            - dockerhub
          requires: 
              - test
          filters:
            branches:
              only: master
      - deploy32:
          context:
            - dockerhub
          requires: 
              - test
          filters:
            branches:
              only: esp32
      - deploy8266:
          context:
            - dockerhub
          requires: 
              - test
          filters:
            branches:
              only: esp8266